/**
 * 考试静态数据库
 * 以EXAM_DB为基准，所有考试相关服务都使用此静态数据
 */

import type { ExamDetail } from '../types/business';

export const EXAM_DB: Record<string, ExamDetail | undefined> = {
  cet4: {
    id: 'cet4',
    name: '英语四级',
    icon: '/images/icons/exam/cte.svg',
    color: 'blue',
    desc: '',
    organizer: '教育部考试中心',
    tagline: '教育部主办的全国大学英语水平测试',
    frequency: '每年6月、12月各一次，通常3月和9月开放报名',
    timeSource: '本期时间仅供参考，请以教育部考试中心当年公告为准！！！',
    timeline: [
      {
        label: '网上报名',
        date: '',
        time: '',
        source: '学校教务处公告',
        note: '',
      },
      {
        label: '报名截止',
        date: '',
        time: '',
        source: '学校教务处公告',
        note: '',
      },
      {
        label: '准考证打印',
        date: '',
        time: '',
        source: '学校教务处公告',
        note: '可在报名网站下载打印',
      },
      {
        label: '口语考试',
        date: '',
        time: '',
        source: '学校教务处公告',
        note: '口语为单独报名，往年通常在笔试前数周内，以准考证上为主',
      },
      {
        label: '笔试',
        date: '',
        time: '09:00',
        source: '教育部公告',
        note: '',
      },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '教育部公告',
        note: '往年通常在笔试后3-4月，以教育部公告为准',
      },
    ],
    info: [
      { label: '主办方', value: '教育部考试中心' },
      { label: '满分', value: '710分' },
      { label: '考试费用', value: '约25元（各省标准不同）' },
      { label: '证书用途', value: '求职、升学、部分学校毕业要求' },
    ],
    subjects: [
      { name: '写作', score: '106.5分', desc: '命题作文' },
      { name: '听力', score: '248.5分', desc: '长对话、听力理解、讲座报告' },
      { name: '阅读', score: '248.5分', desc: '词汇理解、长篇阅读、仔细阅读' },
      { name: '翻译', score: '106.5分', desc: '汉译英段落翻译' },
    ],
    mustKnow: [
      '须持有效居民身份证原件入场，不接受其他证件',
      '考试全程禁止携带手机及任何电子设备',
      '迟到15分钟后不得入场',
      '具体入场规定请以当年准考证及考生须知为准',
    ],
    links: [
      {
        icon: '📋',
        label: '官方报名网站',
        desc: '报名、缴费、准考证下载',
        url: 'https://cet-kw.neea.edu.cn/',
        primary: true,
      },
      {
        icon: '📊',
        label: '成绩查询',
        desc: '考后可在此查询本人成绩',
        url: 'https://cjcx.neea.edu.cn/xhtml1/folder/21033/653-1.htm',
      },
      {
        icon: '📄',
        label: '考试官网',
        desc: '考试动态、考试大纲、常见问题',
        url: 'https://cet.neea.edu.cn/',
      },
      {
        icon: '🎓',
        label: '电子成绩报告单',
        desc: '查询历史成绩并下载电子成绩报告单',
        url: 'https://cjcx.neea.edu.cn/xhtml1/folder/21045/4883-1.htm',
      },
    ],
  },

  cet6: {
    id: 'cet6',
    name: '英语六级',
    icon: '/images/icons/exam/cte.svg',
    color: 'blue',
    organizer: '教育部考试中心',
    desc: '',
    tagline: '教育部主办的全国大学英语水平测试',
    frequency: '每年6月、12月各一次，通常3月和9月开放报名',
    timeSource: '本期时间仅供参考，请以教育部考试中心当年公告为准！！！',
    timeline: [
      {
        label: '网上报名',
        date: '',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '报名截止',
        date: '2026-03-31',
        time: '23:59',
        source: '教育部公告',
        note: '',
      },
      {
        label: '准考证打印',
        date: '',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '笔试',
        date: '',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '教育部公告',
        note: '往年通常在笔试后3-4周，以教育部公告为准',
      },
    ],
    info: [
      { label: '主办方', value: '教育部考试中心' },
      { label: '满分', value: '710分' },
      { label: '考试费用', value: '约25元（各省标准不同）' },
      { label: '证书用途', value: '求职、升学、研究生入学参考' },
    ],
    subjects: [
      { name: '写作', score: '106.5分', desc: '命题作文' },
      { name: '听力', score: '248.5分', desc: '长对话、听力理解、讲座报告' },
      { name: '阅读', score: '248.5分', desc: '词汇理解、长篇阅读、仔细阅读' },
      { name: '翻译', score: '106.5分', desc: '汉译英段落翻译' },
    ],
    mustKnow: [
      '须持有效居民身份证原件入场',
      '考试全程禁止携带手机及任何电子设备',
      '迟到15分钟后不得入场',
      '具体规定请以当年准考证及考生须知为准',
    ],
    links: [
      {
        icon: '📋',
        label: '官方报名网站',
        desc: '报名、缴费、准考证下载',
        url: 'https://cet-kw.neea.edu.cn/',
        primary: true,
      },
      {
        icon: '📊',
        label: '成绩查询',
        desc: '考后可在此查询本人成绩',
        url: 'https://cjcx.neea.edu.cn/xhtml1/folder/21033/653-1.htm',
      },
      {
        icon: '📄',
        label: '考试官网',
        desc: '考试动态、考试大纲、常见问题',
        url: 'https://cet.neea.edu.cn/',
      },
      {
        icon: '🎓',
        label: '电子成绩报告单',
        desc: '查询历史成绩并下载电子成绩报告单',
        url: 'https://cjcx.neea.edu.cn/xhtml1/folder/21045/4883-1.htm',
      },
    ],
  },

  putonghua: {
    id: 'putonghua',
    name: '普通话水平测试',
    icon: '/images/icons/exam/putonghua.svg',
    color: 'orange',
    desc: '',
    organizer: '教育部语言文字工作委员会',
    tagline: '教育部语言文字工作委员会组织的普通话等级测试',
    frequency: '各地全年滚动安排，具体场次以当地测试机构通知为准',
    timeSource: '报名及考试时间以各地语言文字工作委员会或测试机构通知为准',
    timeline: [
      {
        label: '报名',
        date: '',
        time: '',
        source: '当地测试机构',
        note: '各地滚动安排，请关注当地通知',
      },
      { label: '测试', date: '', time: '', source: '当地测试机构', note: '' },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '当地测试机构',
        note: '以当地测试机构通知为准',
      },
    ],
    info: [
      { label: '主办方', value: '教育部语言文字工作委员会' },
      { label: '等级划分', value: '一甲、一乙、二甲、二乙、三甲、三乙' },
      { label: '考试费用', value: '各地不同，以当地通知为准' },
      { label: '证书用途', value: '教师资格、播音主持、部分职业上岗要求' },
    ],
    subjects: [
      { name: '读单音节字词', score: '', desc: '100个字词，限时3.5分钟' },
      { name: '读多音节词语', score: '', desc: '100个词语，限时2.5分钟' },
      { name: '朗读短文', score: '', desc: '400字短文，限时4分钟' },
      { name: '命题说话', score: '', desc: '就指定话题说话，限时3分钟' },
    ],
    mustKnow: [
      '须持有效身份证件参加测试',
      '部分地区采用机器测试，请提前了解当地安排',
      '具体测试规定以当地测试机构通知为准',
    ],
    links: [
      {
        icon: '📋',
        label: '普通话报名系统',
        desc: '报名、报名查询、准考证打印',
        url: 'https://bm.cltt.org/',
        primary: true,
      },
      {
        icon: '📊',
        label: '成绩查询',
        desc: '普通话水平测试成绩查询',
        url: 'https://zwfw.moe.gov.cn/mandarin/',
      },
      {
        icon: '📄',
        label: '国家普通话水平测试网',
        desc: '政策法规、测试报名、查分验证',
        url: 'https://www.cltt.org/',
      },
    ],
  },

  ncre: {
    id: 'ncre',
    name: '全国计算机等级考试',
    icon: '/images/icons/exam/computer.svg',
    color: 'purple',
    desc: '',
    organizer: '教育部考试中心',
    tagline: '教育部考试中心主办的计算机应用能力考试',
    frequency: '每年3月和9月各举办一次',
    timeSource: '本期时间以教育部考试中心当年公告为准',
    timeline: [
      {
        label: '网上报名',
        date: '2026-07-01',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '报名截止',
        date: '2026-07-31',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '上机考试',
        date: '2026-09-20',
        time: '',
        source: '教育部公告',
        note: '具体考试时间段以准考证为准',
      },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '教育部公告',
        note: '往年通常在考后约一个月，以官方公告为准',
      },
    ],
    info: [
      { label: '主办方', value: '教育部考试中心' },
      { label: '级别划分', value: '一级至四级，各级考查方向不同' },
      { label: '考试费用', value: '各地不同，以当地通知为准' },
      { label: '考试形式', value: '上机考试' },
      { label: '证书用途', value: '就业、升学、部分职业上岗要求' },
    ],
    subjects: [
      { name: '一级', score: '', desc: '计算机基础及办公软件' },
      { name: '二级', score: '', desc: '程序设计及办公软件高级应用' },
      { name: '三级', score: '', desc: '网络技术、数据库、信息安全等方向' },
      { name: '四级', score: '', desc: '网络工程师、数据库工程师等方向' },
    ],
    mustKnow: [
      '须持有效居民身份证原件入场',
      '不同级别考试科目不同，报名前请确认所报级别',
      '具体规定请以当年准考证及考生须知为准',
    ],
    links: [
      {
        icon: '📋',
        label: '官方报名网站',
        desc: '报名、缴费、准考证下载',
        url: 'https://ncre-bm.neea.edu.cn/',
        primary: true,
      },
      {
        icon: '📊',
        label: '成绩查询',
        desc: '查询近四个考次考试成绩',
        url: 'https://cjcx.neea.edu.cn/xhtml1/folder/22014/5476-1.htm',
      },
      {
        icon: '🎓',
        label: '证书查询',
        desc: '查询1994年及以后考试证书',
        url: 'https://zscx.neea.edu.cn/xhtml1/folder/22014/5504-1.htm',
      },
      {
        icon: '📄',
        label: '考试官网',
        desc: '考试动态、考试介绍、大纲教材',
        url: 'https://ncre.neea.edu.cn/',
      },
    ],
  },

  teacher: {
    id: 'teacher',
    name: '教师资格证',
    icon: '/images/icons/exam/teacher.svg',
    color: 'green',
    desc: '',
    organizer: '教育部考试中心',
    tagline: '教育部统一组织的教师职业资格认定考试',
    frequency: '笔试每年3月、11月各一次，面试由各省另行安排',
    timeSource: '笔试时间以教育部公告为准，面试时间以各省教育局通知为准',
    timeline: [
      {
        label: '笔试报名',
        date: '2026-09-01',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '报名截止',
        date: '2026-09-30',
        time: '',
        source: '教育部公告',
        note: '',
      },
      {
        label: '准考证打印',
        date: '',
        time: '',
        source: '教育部公告',
        note: '往年通常在笔试前一周，以官方公告为准',
      },
      {
        label: '笔试',
        date: '2026-11-01',
        time: '',
        source: '教育部公告',
        note: '具体时间段以准考证为准',
      },
      {
        label: '笔试成绩',
        date: '',
        time: '',
        source: '教育部公告',
        note: '往年通常在笔试后一个月',
      },
    ],
    info: [
      { label: '主办方', value: '教育部考试中心' },
      { label: '学段划分', value: '幼儿、小学、中学、中职、高校' },
      {
        label: '考试费用',
        value: '笔试每科70元，面试200-300元（各省标准不同）',
      },
      { label: '证书用途', value: '从事教师职业的必要资质' },
    ],
    subjects: [
      { name: '综合素质', score: '150分', desc: '教育理念、教师伦理、法律等' },
      {
        name: '教育知识与能力',
        score: '150分',
        desc: '教育学、心理学等基础知识',
      },
      {
        name: '学科知识与教学能力',
        score: '150分',
        desc: '具体学科知识和教学能力',
      },
      { name: '面试', score: '满分100分', desc: '试讲、答辩、仪表等' },
    ],
    mustKnow: [
      '须持有效居民身份证原件入场',
      '普通话水平等级要求为二级乙等以上',
      '体检和资格认定等环节请关注当地教育局通知',
    ],
    links: [
      {
        icon: '📋',
        label: '报名入口',
        desc: '选择省份并进入报名系统',
        url: 'https://ntce.neea.edu.cn/xhtml1/folder/16013/15-1.htm',
        primary: true,
      },
      {
        icon: '📊',
        label: '成绩查询',
        desc: '查询笔试或面试成绩',
        url: 'https://cjcx.neea.edu.cn/xhtml1/folder/21064/9282-1.htm',
      },
      {
        icon: '📄',
        label: '合格证明查询',
        desc: '查询中小学教师资格考试合格证明',
        url: 'https://zscx.neea.edu.cn/xhtml1/folder/2205/1792-1.htm',
      },
      {
        icon: '🏫',
        label: '资格认定',
        desc: '笔面试通过后的教师资格认定',
        url: 'https://www.jszg.edu.cn/',
      },
      {
        icon: '🏛️',
        label: '考试官网',
        desc: '考试动态、项目政策、资料下载',
        url: 'https://ntce.neea.edu.cn/',
      },
    ],
  },
  kaoyan: {
    id: 'kaoyan',
    name: '全国硕士研究生招生考试',
    icon: '/images/icons/exam/graduate.svg',
    color: 'indigo',
    desc: '',
    organizer: '教育部教育考试院',
    tagline: '全国硕士研究生招生统一考试',
    frequency: '每年一次，通常于前一年12月下旬初试',
    timeSource: '2026年时间以教育部教育考试院及研招网公告为准；后续年度未公布前请留空',
    timeline: [
      {
        label: '网上预报名',
        date: '2025-10-10',
        time: '09:00',
        source: '研招网公告',
        note: '预报名时间为2025年10月10日至10月13日，每日9:00-22:00',
      },
      {
        label: '预报名截止',
        date: '2025-10-13',
        time: '22:00',
        source: '研招网公告',
        note: '',
      },
      {
        label: '网上报名',
        date: '2025-10-16',
        time: '09:00',
        source: '研招网公告',
        note: '正式报名时间为2025年10月16日至10月27日，每日9:00-22:00',
      },
      {
        label: '报名截止',
        date: '2025-10-27',
        time: '22:00',
        source: '研招网公告',
        note: '',
      },
      {
        label: '网上确认',
        date: '',
        time: '',
        source: '省级教育招生考试机构公告',
        note: '各省级教育招生考试机构确定并公布',
      },
      {
        label: '准考证打印',
        date: '2025-12-10',
        time: '',
        source: '研招网',
        note: '研招网报名系统显示为12月10日开始',
      },
      {
        label: '初试',
        date: '2025-12-20',
        time: '',
        source: '教育部教育考试院公告',
        note: '初试时间为2025年12月20日至21日',
      },
    ],
    info: [
      { label: '主办方', value: '教育部教育考试院' },
      { label: '考试性质', value: '研究生招生入学考试' },
      { label: '报名平台', value: '中国研究生招生信息网' },
      { label: '考试用途', value: '硕士研究生招生初试' },
    ],
    subjects: [
      { name: '思想政治理论 / 管理类综合能力', score: '', desc: '按报考专业确定' },
      { name: '外国语', score: '', desc: '按报考专业确定' },
      { name: '业务课一', score: '', desc: '按招生单位专业目录确定' },
      { name: '业务课二', score: '', desc: '按招生单位专业目录确定' },
    ],
    mustKnow: [
      '须在规定时间内完成网上报名和网上确认',
      '网上确认时间由各省级教育招生考试机构公布',
      '具体考试科目与考点安排以准考证和招生单位要求为准',
    ],
    links: [
      {
        icon: '📋',
        label: '研招网报名系统',
        desc: '网上报名、准考证下载',
        url: 'https://yz.chsi.com.cn/yzwb/',
        primary: true,
      },
      {
        icon: '📄',
        label: '2026年报名公告',
        desc: '研招网官方报名公告',
        url: 'https://yz.chsi.com.cn/kyzx/other/202509/20250930/2293435905.html',
      },
      {
        icon: '🏫',
        label: '中国研究生招生信息网',
        desc: '院校信息、专业目录、调剂信息',
        url: 'https://yz.chsi.com.cn/',
      },
    ],
  },

  guokao: {
    id: 'guokao',
    name: '国家公务员考试',
    icon: '/images/icons/exam/government.svg',
    color: 'red',
    desc: '',
    organizer: '国家公务员局',
    tagline: '中央机关及其直属机构考试录用公务员',
    frequency: '每年一次，通常前一年10月报名、11月底或12月初笔试',
    timeSource: '2026年度时间以国家公务员局专题网站公告为准；后续年度未公布前请留空',
    timeline: [
      {
        label: '公告发布',
        date: '2025-10-14',
        time: '',
        source: '国家公务员局',
        note: '',
      },
      {
        label: '网上报名',
        date: '2025-10-15',
        time: '08:00',
        source: '国家公务员局',
        note: '报名时间为2025年10月15日8:00至10月24日18:00',
      },
      {
        label: '报名截止',
        date: '2025-10-24',
        time: '18:00',
        source: '国家公务员局',
        note: '',
      },
      {
        label: '公共科目笔试',
        date: '2025-11-30',
        time: '09:00',
        source: '国家公务员局',
        note: '行测9:00-11:00，申论14:00-17:00',
      },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '国家公务员局',
        note: '以专题网站后续公告为准',
      },
    ],
    info: [
      { label: '主办方', value: '国家公务员局' },
      { label: '考试性质', value: '中央机关及其直属机构公务员录用考试' },
      { label: '考试费用', value: '各地标准不同，以报名确认页面为准' },
      { label: '证书用途', value: '公务员招录' },
    ],
    subjects: [
      { name: '行政职业能力测验', score: '', desc: '公共科目笔试' },
      { name: '申论', score: '', desc: '公共科目笔试' },
      { name: '专业科目', score: '', desc: '部分职位设置' },
      { name: '面试', score: '', desc: '按招录机关安排' },
    ],
    mustKnow: [
      '每次只能选报1个职位',
      '资格审查贯穿录用全过程',
      '具体职位条件以职位表和招录机关要求为准',
    ],
    links: [
      {
        icon: '📋',
        label: '2026年度国考专题网站',
        desc: '报名、公告、职位表、成绩查询',
        url: 'https://bm.scs.gov.cn/kl2026',
        primary: true,
      },
      {
        icon: '🏛️',
        label: '国家公务员局',
        desc: '公务员考试录用信息',
        url: 'https://www.scs.gov.cn',
      },
    ],
  },

  cpa: {
    id: 'cpa',
    name: '注册会计师考试',
    icon: '/images/icons/exam/accounting.svg',
    color: 'gold',
    desc: '',
    organizer: '财政部注册会计师考试委员会',
    tagline: '注册会计师全国统一考试',
    frequency: '每年一次，通常4月报名、8月考试',
    timeSource: '2026年时间以中国注册会计师协会公告和报名简章为准',
    timeline: [
      {
        label: '报名开始',
        date: '2026-04-07',
        time: '08:00',
        source: '中注协公告',
        note: '报名时间为2026年4月7日8:00至4月30日20:00',
      },
      {
        label: '报名截止',
        date: '2026-04-30',
        time: '20:00',
        source: '中注协公告',
        note: '',
      },
      {
        label: '交费开始',
        date: '2026-06-15',
        time: '08:00',
        source: '中注协公告',
        note: '交费时间为2026年6月15日至30日，每天8:00-20:00',
      },
      {
        label: '交费截止',
        date: '2026-06-30',
        time: '20:00',
        source: '中注协公告',
        note: '',
      },
      {
        label: '专业阶段考试',
        date: '2026-08-29',
        time: '',
        source: '中注协公告',
        note: '内地及港澳地区专业阶段考试为2026年8月29日至30日',
      },
      {
        label: '综合阶段考试',
        date: '2026-08-30',
        time: '',
        source: '中注协公告',
        note: '',
      },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '中注协公告',
        note: '以中注协后续公告为准',
      },
    ],
    info: [
      { label: '主办方', value: '财政部注册会计师考试委员会' },
      { label: '阶段划分', value: '专业阶段、综合阶段' },
      { label: '报名平台', value: '注册会计师全国统一考试网上报名系统' },
      { label: '证书用途', value: '注册会计师执业资格相关考试' },
    ],
    subjects: [
      { name: '会计', score: '', desc: '专业阶段' },
      { name: '审计', score: '', desc: '专业阶段' },
      { name: '财务成本管理', score: '', desc: '专业阶段' },
      { name: '公司战略与风险管理', score: '', desc: '专业阶段' },
      { name: '经济法', score: '', desc: '专业阶段' },
      { name: '税法', score: '', desc: '专业阶段' },
      { name: '职业能力综合测试', score: '', desc: '综合阶段' },
    ],
    mustKnow: [
      '报名和交费分阶段进行',
      '完成交费后，报考科目、考区及其他报名信息一般不得更改',
      '具体考试场次以准考证为准',
    ],
    links: [
      {
        icon: '📋',
        label: '注会网报系统',
        desc: '报名、交费、准考证下载',
        url: 'https://cpaexam.cicpa.org.cn',
        primary: true,
      },
      {
        icon: '📄',
        label: '2026年考试时间公告',
        desc: '中注协官方公告',
        url: 'https://www.cicpa.org.cn/xxfb/tzgg/202512/t20251210_65740.html',
      },
      {
        icon: '🏛️',
        label: '中注协考试专区',
        desc: '报名简章、考试大纲、考试动态',
        url: 'https://www.cicpa.org.cn/ztzl1/exam/',
      },
    ],
  },

  juniorAccounting: {
    id: 'juniorAccounting',
    name: '初级会计资格考试',
    icon: '/images/icons/exam/accounting.svg',
    color: 'yellow',
    desc: '',
    organizer: '财政部会计财务评价中心',
    tagline: '全国会计专业技术初级资格考试',
    frequency: '每年一次，通常1月报名、5月考试',
    timeSource: '2026年时间以财政部考务日程安排为准',
    timeline: [
      {
        label: '报名开始',
        date: '2026-01-05',
        time: '',
        source: '财政部公告',
        note: '各省级考试管理机构在全国统一开放时间内自行确定本地区报名开始时间',
      },
      {
        label: '报名截止',
        date: '2026-01-27',
        time: '12:00',
        source: '财政部公告',
        note: '',
      },
      {
        label: '缴费截止',
        date: '2026-01-27',
        time: '18:00',
        source: '财政部公告',
        note: '',
      },
      {
        label: '考试',
        date: '2026-05-16',
        time: '',
        source: '财政部公告',
        note: '考试于2026年5月16日至18日举行，共6个批次',
      },
      {
        label: '成绩公布',
        date: '',
        time: '',
        source: '财政部公告',
        note: '以全国会计资格评价网后续通知为准',
      },
    ],
    info: [
      { label: '主办方', value: '财政部会计财务评价中心' },
      { label: '考试级别', value: '初级' },
      { label: '考试形式', value: '无纸化考试' },
      { label: '证书用途', value: '会计专业技术初级资格' },
    ],
    subjects: [
      { name: '初级会计实务', score: '', desc: '考试时长105分钟' },
      { name: '经济法基础', score: '', desc: '考试时长75分钟' },
    ],
    mustKnow: [
      '各地区报名开始时间可能不同',
      '报名截止和缴费截止时间全国统一',
      '两个科目连续考试，时间不能混用',
    ],
    links: [
      {
        icon: '📋',
        label: '全国会计资格评价网',
        desc: '报名、准考证、成绩查询',
        url: 'https://kzp.mof.gov.cn/index.jsp',
        primary: true,
      },
      {
        icon: '📄',
        label: '2026年考务日程安排',
        desc: '财政部官方通知',
        url: 'https://m.mof.gov.cn/tzgg/202511/t20251127_3977584.htm',
      },
    ],
  },

  intermediateAccounting: {
    id: 'intermediateAccounting',
    name: '中级会计资格考试',
    icon: '/images/icons/exam/accounting.svg',
    color: 'amber',
    desc: '',
    organizer: '财政部会计财务评价中心',
    tagline: '全国会计专业技术中级资格考试',
    frequency: '每年一次，通常6月报名、9月考试',
    timeSource: '2026年时间以财政部考务日程安排为准',
    timeline: [
      {
        label: '报名开始',
        date: '2026-06-12',
        time: '',
        source: '财政部公告',
        note: '各省级考试管理机构在全国统一开放时间内自行确定本地区报名开始时间',
      },
      {
        label: '信息采集截止',
        date: '2026-07-01',
        time: '12:00',
        source: '财政部公告',
        note: '',
      },
      {
        label: '报名截止',
        date: '2026-07-02',
        time: '12:00',
        source: '财政部公告',
        note: '',
      },
      {
        label: '缴费截止',
        date: '2026-07-02',
        time: '18:00',
        source: '财政部公告',
        note: '',
      },
      {
        label: '考试',
        date: '2026-09-05',
        time: '',
        source: '财政部公告',
        note: '考试于2026年9月5日至6日举行，共2个批次',
      },
      {
        label: '成绩公布',
        date: '',
        time: '',
        source: '财政部公告',
        note: '以全国会计资格评价网后续通知为准',
      },
    ],
    info: [
      { label: '主办方', value: '财政部会计财务评价中心' },
      { label: '考试级别', value: '中级' },
      { label: '考试形式', value: '无纸化考试' },
      { label: '证书用途', value: '会计专业技术中级资格' },
    ],
    subjects: [
      { name: '中级会计实务', score: '', desc: '考试时长150分钟' },
      { name: '财务管理', score: '', desc: '考试时长120分钟' },
      { name: '经济法', score: '', desc: '考试时长120分钟' },
    ],
    mustKnow: [
      '报名开始时间各地可能不同',
      '报名截止和缴费截止时间全国统一',
      '报名前通常需完成会计人员信息采集',
    ],
    links: [
      {
        icon: '📋',
        label: '全国会计资格评价网',
        desc: '报名、准考证、成绩查询',
        url: 'https://kzp.mof.gov.cn/index.jsp',
        primary: true,
      },
      {
        icon: '📄',
        label: '2026年考务日程安排',
        desc: '财政部官方通知',
        url: 'https://m.mof.gov.cn/tzgg/202511/t20251127_3977584.htm',
      },
    ],
  },

  lawExam: {
    id: 'lawExam',
    name: '国家统一法律职业资格考试',
    icon: '/images/icons/exam/law.svg',
    color: 'slate',
    desc: '',
    organizer: '司法部',
    tagline: '国家统一组织的法律职业资格考试',
    frequency: '每年一次，通常6月报名、9月客观题、10月主观题',
    timeSource: '2026年时间以司法部公告为准',
    timeline: [
      {
        label: '客观题报名开始',
        date: '2026-06-15',
        time: '00:00',
        source: '司法部公告',
        note: '客观题报名时间为2026年6月15日0时至6月29日18时',
      },
      {
        label: '客观题报名截止',
        date: '2026-06-29',
        time: '18:00',
        source: '司法部公告',
        note: '',
      },
      {
        label: '客观题交费截止',
        date: '2026-07-04',
        time: '18:00',
        source: '司法部公告',
        note: '',
      },
      {
        label: '客观题考试',
        date: '2026-09-12',
        time: '',
        source: '司法部公告',
        note: '客观题考试时间为2026年9月12日、13日',
      },
      {
        label: '客观题成绩公布',
        date: '2026-09-19',
        time: '',
        source: '司法部公告',
        note: '',
      },
      {
        label: '主观题报名开始',
        date: '2026-09-19',
        time: '08:00',
        source: '司法部公告',
        note: '主观题确认报名时间为9月19日8时至9月23日18时',
      },
      {
        label: '主观题报名截止',
        date: '2026-09-23',
        time: '18:00',
        source: '司法部公告',
        note: '',
      },
      {
        label: '主观题准考证打印',
        date: '2026-10-13',
        time: '',
        source: '司法部公告',
        note: '10月13日至17日打印',
      },
      {
        label: '主观题考试',
        date: '2026-10-18',
        time: '09:00',
        source: '司法部公告',
        note: '主观题考试时间为9:00-13:00',
      },
    ],
    info: [
      { label: '主办方', value: '司法部' },
      { label: '考试阶段', value: '客观题、主观题' },
      { label: '考试形式', value: '计算机化考试为主' },
      { label: '证书用途', value: '法律职业资格申请' },
    ],
    subjects: [
      { name: '客观题试卷一', score: '150分', desc: '客观题考试' },
      { name: '客观题试卷二', score: '150分', desc: '客观题考试' },
      { name: '主观题试卷', score: '180分', desc: '主观题考试' },
    ],
    mustKnow: [
      '客观题合格后方可确认参加主观题考试',
      '2025年客观题保留有效成绩人员可报名参加2026年主观题',
      '具体考区、考点和批次以准考证为准',
    ],
    links: [
      {
        icon: '📋',
        label: '法考信息服务平台',
        desc: '报名、交费、准考证打印',
        url: 'https://nje.examos.cn/EXAMSF/public/index.jsp',
        primary: true,
      },
      {
        icon: '📄',
        label: '2026年司法部公告',
        desc: '官方考试公告',
        url: 'https://www.moj.gov.cn/pub/sfbgw/zwxxgk/fdzdgknr/fdzdgknrtzwj/202606/t20260605_536058.html',
      },
      {
        icon: '🏛️',
        label: '司法部官网',
        desc: '考试政策与公告',
        url: 'https://www.moj.gov.cn',
      },
    ],
  },

  ruankao: {
    id: 'ruankao',
    name: '软考',
    icon: '/images/icons/exam/computer.svg',
    color: 'cyan',
    desc: '',
    organizer: '工业和信息化部教育与考试中心',
    tagline: '计算机技术与软件专业技术资格（水平）考试',
    frequency: '每年通常安排上半年、下半年两次，具体资格开考批次不同',
    timeSource: '2026年时间以中国计算机技术职业资格网及各地考试机构公告为准',
    timeline: [
      {
        label: '上半年报名',
        date: '',
        time: '',
        source: '各地考试机构公告',
        note: '各地报名时间不同，以当地公告和报名平台为准',
      },
      {
        label: '上半年考试',
        date: '2026-05-23',
        time: '',
        source: '中国计算机技术职业资格网',
        note: '上半年考试日期为2026年5月23日至26日，具体资格和批次以准考证为准',
      },
      {
        label: '下半年报名',
        date: '',
        time: '',
        source: '各地考试机构公告',
        note: '各地报名时间不同，以当地公告和报名平台为准',
      },
      {
        label: '下半年考试',
        date: '2026-10-24',
        time: '',
        source: '中国计算机技术职业资格网',
        note: '下半年考试日期为2026年10月24日至27日，具体资格和批次以准考证为准',
      },
      {
        label: '成绩查询',
        date: '',
        time: '',
        source: '中国计算机技术职业资格网',
        note: '以官网后续通知为准',
      },
    ],
    info: [
      { label: '主办方', value: '工业和信息化部教育与考试中心' },
      { label: '级别划分', value: '初级、中级、高级' },
      { label: '考试形式', value: '计算机化考试' },
      { label: '证书用途', value: '计算机软件专业技术资格与职称相关' },
    ],
    subjects: [
      { name: '初级资格', score: '', desc: '程序员、网络管理员等，具体以当年安排为准' },
      { name: '中级资格', score: '', desc: '软件设计师、网络工程师等，具体以当年安排为准' },
      { name: '高级资格', score: '', desc: '系统分析师、系统架构设计师等，具体以当年安排为准' },
    ],
    mustKnow: [
      '不同资格开考批次不同',
      '报名时间和准考证打印时间各地不同',
      '具体考试日期、批次、地点以准考证为准',
    ],
    links: [
      {
        icon: '📋',
        label: '软考报名平台',
        desc: '报名、缴费、准考证打印',
        url: 'https://bm.ruankao.org.cn/report/index',
        primary: true,
      },
      {
        icon: '🏛️',
        label: '中国计算机技术职业资格网',
        desc: '考试安排、报名入口、成绩查询',
        url: 'https://www.ruankao.org.cn/',
      },
      {
        icon: '📄',
        label: '考试安排',
        desc: '年度考试安排入口',
        url: 'https://www.ruankao.org.cn/exam/plan.html',
      },
    ],
  },
};

/**
 * 获取单个考试详情
 */
export const getExamDetail = (examId: string) => {
  return EXAM_DB[examId];
};

/**
 * 获取考试时间线
 */
export const getExamTimeline = (examId: string) => {
  return EXAM_DB[examId]?.timeline ?? [];
};
